<?php

namespace AppBundle\Repository;

/**
 * CrontaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CrontaskRepository extends \Doctrine\ORM\EntityRepository
{
}
