<?php

namespace AppBundle\Repository;

/**
 * TradeInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TradeInfoRepository extends \Doctrine\ORM\EntityRepository
{
}
