services:
#    api.example:
#        class: ApiBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    api.livecoin:
        class: ApiBundle\Service\Livecoin
        arguments: ["@service_container", "@doctrine.orm.entity_manager"]

    api.bitmex:
        class: ApiBundle\Service\Bitmex
        arguments: ["@service_container", "@doctrine.orm.entity_manager"]

    api.binance:
        class: ApiBundle\Service\Binance
        arguments: ["@service_container", "@doctrine.orm.entity_manager"]

    api.cryptopia:
        class: ApiBundle\Service\Cryptopia
        arguments: ["@service_container", "@doctrine.orm.entity_manager"]

    api.gdax:
        class: ApiBundle\Service\Gdax
        arguments: ["@service_container", "@doctrine.orm.entity_manager"]

    api.hitbtc:
        class: ApiBundle\Service\Hitbtc
        arguments: ["@service_container", "@doctrine.orm.entity_manager"]

    api.huobipro:
        class: ApiBundle\Service\Huobipro
        arguments: ["@service_container", "@doctrine.orm.entity_manager"]

    api.kraken:
        class: ApiBundle\Service\Huobipro
        arguments: ["@service_container", "@doctrine.orm.entity_manager"]